[workspace]
members = [
    "cu", 
    "client-lib",
    "faas", 
    "ao-scheduler-utils", 
    "loader", 
    "ao-common",
    "ar-bundles",
    "rust-sdk",
    "wasmedge-sdk-bindgen"
]
resolver = "2"
