[package]
name = "faas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
anyhow = "1.0.81"
wasmedge-sdk = "0.13.2"
wasmedge-sdk-bindgen = { path = "../wasmedge-sdk-bindgen/" }
wasmedge_quickjs = "0.2.0"