[package]
name = "ar-bundles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64url = "0.1.0"
jsonwebkey = "0.3.5"
once_cell = "1.19.0"
rsa = "0.9.6"
