[package]
name = "ar-bundles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64-url = "2.0.2"
jsonwebkey = { version = "0.3.5", features = ["pkcs-convert"] }
once_cell = "1.19.0"
rsa = "0.9.6"
